# _______  _     _   _________     ______  ______   ______  _    _   ______ 
#   | |   | |   | | | | | | | \   | |     | |  | | | |     | |  | | | |     
#   | |   \ \   / / | | | | | |   | |     | |__| | | |     | |--| | | |---- 
#   |_|    \_\_/_/  |_| |_| |_|   |_|____ |_|  |_| |_|____ |_|  |_| |_|____ 
#                                                                           

CachePath: "/home/thais/Dev/tvm-cache-ms/cache_v4/"

TotalCacheSize: 2500
