# _______  _     _   _________     ______  ______   ______  _    _   ______ 
#   | |   | |   | | | | | | | \   | |     | |  | | | |     | |  | | | |     
#   | |   \ \   / / | | | | | |   | |     | |__| | | |     | |--| | | |---- 
#   |_|    \_\_/_/  |_| |_| |_|   |_|____ |_|  |_| |_|____ |_|  |_| |_|____ 
#                                                                           

#CachePath: "/home/thais.camacho/tvm-cache-ms/cache_paper_cuda/cache-vgg_16-googlenet/"
CachePath: "/home/thais.camacho/tvm-cache-ms/cache_paper_cuda/cache-resnext_50-wide_resnet_50/"
#CachePath: "/home/thais.camacho/tvm-cache-ms/cache_paper_cpu/cache-mobilenet_v2-mobilenet_v3/"

TotalCacheSize: 500

#Target: "llvm -num-cores 24"
Target: "cuda -arch=sm_70 -max_threads_per_block=1024 -thread_warp_size=32 -max_shared_memory_per_block=49152 -registers_per_block=65536"
